namespace ConferenceRoomBookingApi.Application.DTOs.Analytics;

/// <summary>
/// Metric data transfer object representing revenue and booking totals for a conference room.
/// </summary>
public class RoomRevenueDto
{
    /// <summary>
    /// The unique identifier of the room.
    /// </summary>
    /// <example>1</example>
    public int RoomId { get; set; }

    /// <summary>
    /// The display name of the room.
    /// </summary>
    /// <example>Room A</example>
    public string RoomName { get; set; } = string.Empty;

    /// <summary>
    /// Total number of bookings reserved for this room.
    /// </summary>
    /// <example>15</example>
    public int TotalBookings { get; set; }

    /// <summary>
    /// Cumulative revenue generated by this room (in UAH).
    /// </summary>
    /// <example>45000.00</example>
    public decimal TotalRevenue { get; set; }
}
